name = "JuliaDocStringError"
uuid = "f598356f-5cd3-4629-805b-43acb6b5cffb"
authors = ["Daniel P. Egan <dp.egan@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "0.27"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
